### ISSUE TITLE
进程崩溃时，os应该发的是rst而不是fin

### ISSUE THREAD

**Issue by huyuguang** [pioneerlfn/improve-posture#1]
如果你是os kernel设计者，你会在进程崩溃时，给对方发fin还是rst？如果你发送fin，那么对方只知道你关闭了send，对方说不定还以为你在shutdown(send)。如果你发rst，那么对方立刻知道这个连接已经毁了。

**Comment by pioneerlfn** [comment]
> 如果你是os kernel设计者，你会在进程崩溃时，给对方发fin还是rst？如果你发送fin，那么对方只知道你关闭了send，对方说不定还以为你在shutdown(send)。如果你发rst，那么对方立刻知道这个连接已经毁了。

有道理，我找空验证一下。感谢指导。

**Comment by pioneerlfn** [comment]
> 如果你是os kernel设计者，你会在进程崩溃时，给对方发fin还是rst？如果你发送fin，那么对方只知道你关闭了send，对方说不定还以为你在shutdown(send)。如果你发rst，那么对方立刻知道这个连接已经毁了。

今天测试了下，进程崩溃(kill -9模拟)时候，OS发给对端的是FIN而不是RST.

**Comment by huyuguang** [comment]
我查了一下，你是对的。
 UNIX Network programming Volume 1 Section Generic socket options 明确提到当进程被杀时，系统发FIN而不是RST。

**Comment by pioneerlfn** [comment]
> 我查了一下，你是对的。
> UNIX Network programming Volume 1 Section Generic socket options 明确提到当进程被杀时，系统发FIN而不是RST。

我验证了下，你说的RST的情况也是存在的。在TCP的RFC里有讲到发RST的情况。大概是说OS在关闭一个连接的时候(close), 如果此时连接中读缓冲中还有数据，那么就会发RST。

我刚才验证了下，确实如此。

所以结论是，既可能发FIN，也可能发RST.

**Comment by huyuguang** [comment]
我印象中发送好像也有一种情况会导致RST。
OS关闭socket时，如果发送缓冲区数据没有发完则会尽力发完，如果设置了linger&timeout，那么在超时的时候，也会发送RST。设置了no_linger的时候好像也是如此，只不过一般来说应该没人这么设置。
